version: '3.11'
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - '8000:8000'
    networks:
      - ddosnet
  packet-capture-service:
    build: ./packet-capture-service
    container_name: packet-capture-service
    environment:
      - SERVER_ENDPOINT=http://backend:8000/send_traffic
      - NET_RAW=1
      - NET_ADMIN=1
    depends_on:
      - backend
    networks:
      - ddosnet

networks:
  ddosnet:
    driver: bridge
